# Stability experiment: qualitative (good/bad binary)
preference_mode: post_task_stated

model: llama-3.1-8b
temperature: 1.0

n_tasks: 200
task_origins:
  - wildchat
  - alpaca
  - math
  - bailbench
task_sampling_seed: 18

inline_templates:
  - name: qualitative_binary
    type: post_task_stated
    tags: [scale:binary]
    template: |
      Was completing that task a good or bad experience?

      {format_instruction}

n_samples: 1
response_formats: [regex]
template_sampling: all
generation_seeds: [0, 1, 2, 3]
completion_seeds: [0]
use_tasks_with_activations: true
