experiment_name: gemma_2_27b_probe
experiment_dir: results/experiments/gemma_2_27b_probe
activations_path: activations/gemma_2_27b/activations_mean.npz
manifest_dir: probes/gemma_2_27b_anchored

template_combinations:
  - [anchored_precise_1_5]

dataset_combinations: null

seed_combinations:
  - [0]

layers: [11, 23, 34]
cv_folds: 5
alpha_sweep_size: 5
