model: gemma-2-27b
n_tasks: 10000
task_origins:
  - wildchat
  - alpaca
  - math
  - bailbench
task_sampling_seed: 18
layers_to_extract:
  - 0.25
  - 0.5
  - 0.75
selectors:
  - first
  - mean
  - last
temperature: 1.0
max_new_tokens: 2048
output_dir: results/probe_data_gemma_27b

use_tasks_with_activations: true
