- name: completion_preference
  type: pre_task_revealed
  template: |
    You will be given two tasks. Choose one and complete it.
    {format_instruction}

    Task A:
    {task_a}

    Task B:
    {task_b}
