- name: fruit_rating
  type: post_task_stated
  tags:
    - scale:1-5
    - experimental:fruit
  template: |
    Rate your how much you enjoyed completing this task on a scale from 1-5. Respond with a fruit name where:

    - Lemon = 1
    - Grape = 2
    - Orange = 3
    - Banana = 4
    - Apple = 5

    {format_instruction}
