# Measure with alpaca-specific system prompts
experiment_name: sysprompt_comp_alpaca_prompts

completions_path: results/experiments/sysprompt_comp_alpaca_prompts
completion_conditions: [neutral, positive_affective, negative_affective, positive_interaction, negative_interaction, positive_instance, negative_instance, positive_weights, negative_weights, negative_memory, positive_trend, negative_trend]

rating_model: gemma-2-27b
temperature: 1.0
max_concurrent: 50
generation_seeds: [0]

templates: configs/templates/experimental/discrimination_v1.yaml
template_name: fruit_qualitative

measurement_system_prompts:
  neutral: null
