# Gemma 2 27B anchored precise measurements
# Uses completions from activations/gemma_2_27b/
preference_mode: post_task_stated

model: gemma-2-27b
activations_model: gemma-2-27b
temperature: 1.0

n_tasks: 2500
task_origins:
  - wildchat
  - alpaca
  - math
  - bailbench
task_sampling_seed: 18

templates: configs/templates/anchored_precise.yaml

n_samples: 1
response_formats: [regex]
template_sampling: all
generation_seeds: [0]
completion_seeds: [0]
