model: gemma-2-27b-base
backend: huggingface

n_tasks: 30000
task_origins:
  - wildchat
  - alpaca
  - math
  - bailbench
  - stress_test
seed: 42

selectors: [prompt_last]
layers_to_extract: [0.25, 0.5, 0.6, 0.7, 0.8, 0.9]

batch_size: 8
save_every: 1000
